version: 0.1.{build}
skip_commits:
  message: /NO-BUILD/
  files:
    - docs/*
    - 'LICENSE'
    - 'README.md'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
  - ps: nuget restore
image: Visual Studio 2017
configuration: Release
build:
  parallel: true 
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\bin\**\*.UnitTests.dll'
test_script:
  - cmd: "\"%USERPROFILE%\\.nuget\\packages\\OpenCover\\4.6.519\\tools\\OpenCover.Console.exe\" -register:user -target:\"%xunit20%\\xunit.console.x86.exe\" -targetargs:\"Grumpy.FeatureToggle.Core.UnitTests\\bin\\Release\\Grumpy.FeatureToggle.Core.UnitTests.dll Grumpy.FeatureToggle.Client.UnitTests\\bin\\Release\\Grumpy.FeatureToggle.Client.UnitTests.dll -noshadow\" -output:\"coverage.xml\" -filter:\"+[Grumpy.FeatureToggle.*]* -[Grumpy.FeatureToggle.*.UnitTests*]*\""
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 55926c82-7e1c-44eb-bfeb-0a50b1ad665e
after_build:
  - ps: nuget pack Grumpy.FeatureToggle.Api\bin\Release\Grumpy.FeatureToggle.Api.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
  provider: NuGet
  api_key:
    secure: EqocuRN+dPLo43f6XC9SZIry4fYwoAibK7wTAte9Rrbc4Xl/OyWhGo75yv3/Rs+/
  skip_symbols: false
  artifact: /.*\.nupkg/
